# ECG Denoising Experiment Configuration

# Experiment settings
experiment_name: 'exp_denoising'
sampling_frequency: 500  # Hz
random_seed: 42

# Paths
datafolder: '../../data/ptbxl/'
outputfolder: 'output/'
noise_config_path: '../noise/config/default.yaml'

# Data splits (using strat_fold from PTB-XL)
train_fold: 8
val_fold: 9
test_fold: 10

# Data preprocessing
preprocessing:
  bandpass_lowcut: 1.0   # Hz
  bandpass_highcut: 45.0  # Hz
  bandpass_order: 2
  normalization: 'standard'  # 'standard' or 'minmax'

# Models to train
models:
  - name: 'fcn'
    type: 'fcn'
    epochs: 50
    lr: 0.001
    batch_size: 32

  - name: 'unet'
    type: 'unet'
    epochs: 50
    lr: 0.001
    batch_size: 32

  - name: 'imunet'
    type: 'imunet'
    epochs: 50
    lr: 0.001
    batch_size: 32

# Training settings
training:
  optimizer: 'adam'
  loss: 'mse'
  scheduler:
    type: 'ReduceLROnPlateau'
    mode: 'min'
    factor: 0.5
    patience: 5
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0001

# DataLoader settings
dataloader:
  num_workers: 4
  pin_memory: true

# Evaluation settings
evaluation:
  n_bootstrap_samples: 100
  n_jobs: 20
  metrics: ['snr_improvement_db', 'output_snr_db', 'rmse', 'rmse_improvement']

# Output settings
output:
  save_predictions: true
  save_history: true
  generate_plots: true
  n_example_plots: 3

# Hardware settings
hardware:
  use_cuda: true
  deterministic: true
